---
title: "nathan_ida"
author: '490418846'
date: '2022-04-02'
output: html_document
---

```{r}
library(tidyverse)
library(sf)
```

## Storm Data

```{r}
storms_list = read.csv("Data/ibtracs.ALL.list.v04r00.csv")
storms_list = storms_list %>% 
  slice(-1) %>%
  select(SID, SEASON, LAT, LON, STORM_SPEED, STORM_DIR) %>%
  mutate(SEASON = as.numeric(SEASON)) %>%
  filter(SEASON >= 1997) %>%
  mutate(LAT = as.numeric(LAT)) %>%
  mutate(LON = as.numeric(LON)) %>%
  mutate(STORM_SPEED = as.numeric(STORM_SPEED)) %>%
  mutate(STORM_DIR = as.numeric(STORM_DIR)) %>%
  drop_na()
storms_list
```

## Benthic Map Data

```{r}
benthic = st_read("Data/benthic.gpkg")
geom = lapply(benthic$geom, st_bbox)
bbox_vector = c()
for (i in 1:length(geom)) {
  bbox_vector = rbind(bbox_vector, t(matrix(unlist(geom[[i]]))))
}
benthic = as.data.frame(cbind(benthic$class, bbox_vector))
colnames(benthic) = c("Class", "xmin", "ymin", "xmax", "ymax")
benthic = benthic %>%
  mutate(xmin = as.numeric(xmin)) %>%
  mutate(ymin = as.numeric(ymin)) %>%
  mutate(xmax = as.numeric(xmax)) %>%
  mutate(ymax = as.numeric(ymax))
benthic
```

## Geomorphic data

```{r}
geomorphic = st_read("Data/geomorphic.gpkg")
geom = lapply(geomorphic$geom, st_bbox)
bbox_vector = c()
for (i in 1:length(geom)) {
  bbox_vector = rbind(bbox_vector, t(matrix(unlist(geom[[i]]))))
}
geomorphic = as.data.frame(cbind(geomorphic$class, bbox_vector))
colnames(geomorphic) = c("Class", "xmin", "ymin", "xmax", "ymax")
geomorphic = geomorphic %>%
  mutate(xmin = as.numeric(xmin)) %>%
  mutate(ymin = as.numeric(ymin)) %>%
  mutate(xmax = as.numeric(xmax)) %>%
  mutate(ymax = as.numeric(ymax))
geomorphic
```

## Reef data

```{r}
reef_df = read.csv("Data/Reef_Check_with_cortad_variables_with_annual_rate_of_SST_change.csv")
reef_df = reef_df %>% 
  drop_na(Longitude.Degrees) %>%
  drop_na(Latitude.Degrees) %>%
  mutate(Date = as.Date(Date, "%d-%b-%y"))

calculate_degrees = function(degrees, minutes, seconds) {
  return (degrees + minutes/60 + seconds/3600)
}

# reef_df$Longitude.Decimal = mapply(calculate_degrees, reef_df$Longitude.Degrees, reef_df$Longitude.Minutes, reef_df$Longitude.Seconds)
# reef_df$Latitude.Decimal = mapply(calculate_degrees, reef_df$Latitude.Degrees, reef_df$Latitude.Minutes, reef_df$Latitude.Seconds)
reef_df$geom = reef_df %>% st_as_sf(coords = c("Longitude.Degrees", "Latitude.Degrees"),crs=4326)
```

```{r}
reef_df
```

## Merged dataset

```{r}
reef_geomorphic = st_read("Data/reef_geomorphic_joined.gpkg")
reef_geomorphic = reef_geomorphic %>% 
  as.data.frame() %>%
  mutate(Date = as.Date(Date, "%d-%b-%y")) %>%
  mutate(Depth = as.numeric(Depth)) %>%
  filter(Depth <= 15)

reef_geomorphic
```

```{r}
not_na = reef_geomorphic %>% 
  slice(which(!is.na(reef_geomorphic$class))) %>%
  select(Reef.ID, Depth, Average_bleaching, class) %>%
  as.data.frame()

not_na # 1187

not_na %>% distinct(Reef.ID, Depth, class) # 685

not_na %>% distinct(Reef.ID, Depth) # 685
```

